### ISSUE TITLE
[BUG] Coverage badge not working with SSO for repo

### ISSUE THREAD

**Issue by erickmartins** [TheJacksonLaboratory/ezomero#106]
**Describe the bug**
With JAX now being an SSO org on github, the process we are using for automatically committing a coverage badge does not work any longer.

**Comment by erickmartins** [comment]
tagging @jax-sobolewski on request

**Comment by psobolewskiPhD** [comment]
So within the JAX org, the default token used by GitHub Actions (GITHUB_TOKEN) has only `read` permissions by default.
Previously you could have set it to Read/Write on the repo level.
So now by default the Action cannot make a commit to the repo to update the badge.
The solution is to explicitly provide granular permissions in each workflow.
PR incominig
