### ISSUE TITLE
[BUG] Pages outdated

### ISSUE THREAD

**Issue by TorecLuik** [TheJacksonLaboratory/ezomero#117]
**Describe the bug**
Pages are outdated, needs a rebuild after (every) release

**To Reproduce**
Go to https://thejacksonlaboratory.github.io/ezomero/ezomero.html#ezomero.ezimport , it doesn't mention kwargs and still uses ln_s bool notation.

**Expected behavior**
Kwargs mentioned in ezimport pages

**Screenshots**

**Desktop (please complete the following information):**
 - Python version [e.g. 3.6.11, 3.7]
 - ezomero version 3.1.0

**Additional context**

**Comment by erickmartins** [comment]
Thanks for the report - yeah, I think documentation fell behind a few versions. I'll push a PR updating it.

**Comment by erickmartins** [comment]
#120 should gives us a sustainable solution for this - documentation will be updated with every release from now on.

**Comment by erickmartins** [comment]
Documentation should be up-to-date with main and will now be rebuilt with every release. Closing this.
