### ISSUE TITLE
across_groups flag being ignored

### ISSUE THREAD

**Issue by mellertd** [TheJacksonLaboratory/ezomero#19]
line 55 in _ezomero.py should be fixed (change `or` to `and`) so that across groups parameter is respected

we also need a test to catch this failure

**Comment by erickmartins** [comment]
Rather than changing it to `or`, we probably want to:

1) test whether `kwargs['across_groups']` exists at all (i.e. user is overriding defaults);
2) if it exists, respect user setting;
3) if it doesn't, respect `defaults['across_groups']`

**Comment by erickmartins** [comment]
Fixed on PR #20
