### ISSUE TITLE
Creating file annotations / attachments

### ISSUE THREAD

**Issue by abhamacher** [TheJacksonLaboratory/ezomero#21]
Hi all,

I really love the idea of ezomero! Have you thought yet about including an easy command to create file annotations? The use case I have mainly in my mind is about accessing images via the python API, doing some image analysis and calculations on them, creating plots, etc. and then pushing results back to Omero as attachment (not as Omero tables).

Happy to test this of course.

BR and thanks for the great work
Anna

**Comment by mellertd** [comment]
Just adding to this, we probably should also have a get_original_file or something like that

**Comment by mellertd** [comment]
covered in #23. @abhamacher please try and give feedback! (if you don't want to wait until our next release, you will have to clone the repo)
