### ISSUE TITLE
Split up `_ezomero.py`

### ISSUE THREAD

**Issue by erickmartins** [TheJacksonLaboratory/ezomero#22]
That thing is starting to be unwieldy. Maybe `_ezomero_get.py`, `_ezomero_post.py`, `_ezomero_put.py` and `_ezomero_misc.py`? I don't think we need submodules, just separate files for clarity.

**Comment by mellertd** [comment]
you only need the leading underscore on _ezomero.py, which is really just to avoid namespace weirdness. But in general, I am in favor of breaking up
