### ISSUE TITLE
[FEATURE] post_image reorder axis

### ISSUE THREAD

**Issue by romainGuiet** [TheJacksonLaboratory/ezomero#29]
**Is your feature request related to a problem? Please describe.**
The default **get_Image** return *tzxyc*, and the default **post_image** expects *xyzct*

**Describe the solution you'd like**
In  **get_Image** you can specify if *xyzct=False/True*, I was thinking that it would be convenient if the **post_image** would have something similar and thus would take care of the axis re-ordering
For example, giving the input dimension order as a string argument, and the **post_image** takes care of the re-ordering.

**Describe alternatives you've considered**
Take care of reordering between get_image and post_image, using np.moveaxis

**Comment by mellertd** [comment]
what about taking ordering as a string? So you have a parameter like `dim_order = 'xyzct'` or `dim_order = 'tzyxc'` or anything you want?

**Comment by romainGuiet** [comment]
>what about taking ordering as a string? So you have a parameter like dim_order = 'xyzct' or dim_order = 'tzyxc' or anything you want?

Specifying the input dim_order and having the post_image making the moveaxis to fit the expected order looks perfect!
