### ISSUE TITLE
[FEATURE] Getting Tag annotations

### ISSUE THREAD

**Issue by romainGuiet** [TheJacksonLaboratory/ezomero#30]
**Is your feature request related to a problem? Please describe.**
From [ezomero doc.](https://thejacksonlaboratory.github.io/ezomero/ezomero.html#module-ezomero) and from the [omero annotations doc.](https://docs.openmicroscopy.org/omero/5.6.3/developers/Model/StructuredAnnotations.html) I understand we can retrieve **map_annotations** (*A list of key-value pairs*), and **file_annotation** (*like pdf from omer.ofigure*). Do you plan to get other annotations, like *tags* ?

**Comment by mellertd** [comment]
This is definitely doable, the question is what should a returned tag look like?

I think I would have a function that is something like `get_tag_ids` for getting the ids of tags for an OMERO object, similar to how we deal with other annotations. From there you can of course use `conn.getObjects` to get the wrapped TagAnnotation objects, but I assume you want something a little more straightforward? Like returning just the tag name?

So something like this:
```
>>> tag_ids = ezomero.get_tag_ids(conn, 'Image', im_id)
>>> tags = [ezomero.get_tag(conn, tag_id) for tag_id in tag_ids]
>>> print(tags)
['tag1', 'tag2', 'tag3']
```
?

**Comment by romainGuiet** [comment]
>Like returning just the tag name?

Exactly! The solution you proposed looks awesome!

Cheer

**Comment by erickmartins** [comment]
PR #32 implements this.
