### ISSUE TITLE
Specifying range in get_image

### ISSUE THREAD

**Issue by juliomateoslangerak** [TheJacksonLaboratory/ezomero#4]
I see that you may specify a region when you use get_image using start_coords and axis_lengths. I implemented something similar but using axis specific ranges. Like so:
``` python
def get_image(image_id, z_range=None, c_range=None, t_range=None, y_range=None, x_range=None)
```
the idea being that a range for a specific axis could be specified either as an int or using the range notation. Essentially you reach the same but I find it is more clear in the usage as you clearly specify the dimension. 
Also, you may specify an interval, for example t_range=(0, 20, 2) would get every second time point.

What do you think?

**Comment by erickmartins** [comment]
I don't think we're implementing this, to be honest - it would be a significant rework without too much benefit right now. I'm closing it for now.
