### ISSUE TITLE
[FEATURE] Add optional `group` argument to `post_dataset` and `post_image`

### ISSUE THREAD

**Issue by erickmartins** [TheJacksonLaboratory/ezomero#48]
Currently, "orphaned" (i.e. not posted directly to a containing structure) datasets and images are always posted to the user's default group, no matter what the group specified in `conn` is. We should either have an optional `group` parameter or honor the group in `conn`.

**Comment by mellertd** [comment]
I am going to take a crack at fixing the function to respect `conn`

**Comment by mellertd** [comment]
I most certainly did not take a crack at this. But it's fixed now in #49
