### ISSUE TITLE
[BUG] unexpected indentation on line 480 of _gets.py

### ISSUE THREAD

**Issue by mellertd** [TheJacksonLaboratory/ezomero#62]
**Describe the bug**
we are missing a space on line 480 of `_gets.py` and that seems to be breaking the sphinx docs for `get_project_ids`

**To Reproduce**
build the docs

**Expected behavior**
there should be no unexpected indentation error, and the documentation should render correctly

**Comment by erickmartins** [comment]
should be fixed in #64 .
