### ISSUE TITLE
[FEATURE] Add DOI

### ISSUE THREAD

**Issue by erickmartins** [TheJacksonLaboratory/ezomero#66]
ezomero should have a DOI!

**Comment by perlman** [comment]
The Zenodo route? Or via published preprint somewhere?

**Comment by erickmartins** [comment]
For now just Zenodo, probably. Eventually we'll get something preprinted for this, but not anytime soon

**Comment by mellertd** [comment]
https://doi.org/10.1101/2023.06.29.546930 biorxiv

**Comment by mellertd** [comment]
we should add a reference to the paper and DOI to the readme in an upcoming PR

**Comment by erickmartins** [comment]
Included in #85.
