### ISSUE TITLE
Handle non-existing/inaccessible objects 

### ISSUE THREAD

**Issue by erickmartins** [TheJacksonLaboratory/ezomero#7]
We currently let exceptions happen if you look for an object/try to use an object that does not exist or is inaccessible due to group permissions. We should probably be catching those and failing more gracefully.

**Comment by mellertd** [comment]
Did you cover this in the cross group PR?

**Comment by erickmartins** [comment]
Yes, this is covered for  the functions that are doing cross-group queries as of #17.
