### ISSUE TITLE
[FEATURE] Getting Comment annotations

### ISSUE THREAD

**Issue by raymond301** [TheJacksonLaboratory/ezomero#77]
Similar to issue #30 
I'm not finding the API to pull out comments. 
I tried a couple of common sense combinations just to be sure.

![image](https://github.com/TheJacksonLaboratory/ezomero/assets/392344/e5497c06-0930-41f9-9938-a6c2ce307f74)

![image](https://github.com/TheJacksonLaboratory/ezomero/assets/392344/5984d634-8519-4ea8-af40-10f52be4ddf3)

If there is a way to currently retrieve the comments provided by collaborators on an image, through this EzOMERO wrapper? I'd appreciate it being documented more clearly. Otherwise, can we get these functions added to the package as well?

**Comment by erickmartins** [comment]
Hi! A full list of ezomero functions can be found at https://thejacksonlaboratory.github.io/ezomero/ezomero.html. At the moment there are no functions for adding/retrieving comments, but that is potentially useful - I will leave this issue open.

**Comment by erickmartins** [comment]
Covered in #79.

**Comment by mellertd** [comment]
This is merged, but we haven't built docs yet.

**Comment by erickmartins** [comment]
Included in 2.1.0 release.
