### ISSUE TITLE
using ezomero test infrastructure

### ISSUE THREAD

**Issue by juliomateoslangerak** [TheJacksonLaboratory/ezomero#81]
I love the test infrastructure that you have put in place here and I would like to use it in another OMERO project. I would not know how to copy this and give the credit other than asking you to open a pull request with the test directory to our project.

Would you be ok to do that? Any other idea?

**Comment by erickmartins** [comment]
Hi Julio,

ezomero code is GPLv2 - while we would love to be credited somewhere in an informal way, that is not _strictly_ necessary. Remember your test code will also need to be GPLv2. The `tests` folder is pretty self-contained and has plenty of test examples, plus everything you need to run them - if you have a local clone of the repo you should be able to just copy it to your new project and start developing against it. We're happy to answer any questions you have about it.

**Comment by juliomateoslangerak** [comment]
Hi,
Thanks. I will see how I can acknowledge this somewhere. 
BTW, the package in question is micrsocopemetrics-omero.

Cheers, Julio
