### ISSUE TITLE
[BUG] post_roi() for polygon and polyline not working 

### ISSUE THREAD

**Issue by n-loureiro** [TheJacksonLaboratory/ezomero#90]
**Describe the bug**
When trying to import a Polygon or Polyline, there is no error but ROI will not import correctly.

**To Reproduce**
Create a Polygon by providing a list of points in the requested format: `List[Tuple[float, float]]`. Add to `post_roi` in a selected image and nothing happens

Example:
```
polygon = ezomero.rois.Polygon([(100,200) (200,100) (100,300)]) )
ezomero.post_roi(conn=conn, image_id=100, shapes=[polygon])
```

**Expected behavior**
A triangle should be imported as ROI to image with ID 100. But nothing is shown. ROI still shows as imported in the list of ROIs.

**Comments and Possible Resolution**

I tried adding a Pull Request but don't have the permissions. I believe the error can be fixed by removing the `,` from the function `_shape_to_omero_shape`. 

Where it reads 
`points_str = "".join("".join([str(x), ',', str(y), ', ']) for x, y in shape.points)[:-2]` in lines [777](https://github.com/TheJacksonLaboratory/ezomero/blob/a0344396444ebc17807d19f2d981abe166b77a95/ezomero/_posts.py#L777) and [782](https://github.com/TheJacksonLaboratory/ezomero/blob/a0344396444ebc17807d19f2d981abe166b77a95/ezomero/_posts.py#L782) 
it should read 
`points_str = "".join("".join([str(x), ',', str(y), ' ']) for x, y in shape.points)[:-2]`

**Comment by n-loureiro** [comment]
For more context Omero is [expecting a string](https://omero.readthedocs.io/en/stable/developers/Python.html#rois) of point in the format: `x1,y1 x2,y2 x3,y3` and `post_roi` is providing `x1,y1, x2,y2, x3,y3`

**Comment by erickmartins** [comment]
Hi Nuno,

I could not replicate the issue. Running
```
polygon = ezomero.rois.Polygon([(100,200), (200, 100), (100, 300)])
ezomero.post_roi(conn, image_id=3, shapes=[polygon])
```
generated a triangle as it should, using ezomero 2.1.0. Can you double-check you have the latest ezomero version?

**Comment by erickmartins** [comment]
(as a sidenote, the code you provided doesn't run; list elements need to be separated by commas!)

**Comment by n-loureiro** [comment]
Hi Erick, thanks for the quick reply and for looking into this!

Indeed in my example I was missing the commas (that was a mistake, sorry for that). The way you wrote the example is correct and that's the one that is showing the wrong behavior I described in the issue. 

I'm running version 2.1.0 of ezomero. I'm am also running a version of Omero Plus, but I don't think this would be the reason.

I'm surprised this is working for you because Omero's documentation asks for a string of space-separated x,y points in a polygon. See below the variable points, taken from their docs [their docs](https://omero.readthedocs.io/en/stable/developers/Python.html#rois):

```
# create an ROI with a single polygon, setting colors and lineWidth
polygon = omero.model.PolygonI()
polygon.theZ = rint(z)
polygon.theT = rint(t)
polygon.fillColor = rint(rgba_to_int(255, 0, 255, 50))
polygon.strokeColor = rint(rgba_to_int(255, 255, 0))
polygon.strokeWidth = omero.model.LengthI(10, UnitsLength.PIXEL)
points = "10,20 50,150 200,200 250,75"
polygon.points = rstring(points)
polygon.textValue = rstring("test-Polygon")
create_roi(image, [polygon])
```

When I changed the lines I mentioned above in your `_shape_to_omero_shape` function, it started working.
Since we can't find why we have different behaviors I can always fork the code and have a version that works for me. Thanks again for putting this tool out there, much appreciated!

**Comment by erickmartins** [comment]
as late as [5.6.7](https://omero.readthedocs.io/en/v5.6.7/developers/Python.html), their docs had

```
# create an ROI with a single polygon, setting colors and lineWidth
polygon = omero.model.PolygonI()
polygon.theZ = rint(z)
polygon.theT = rint(t)
polygon.fillColor = rint(rgba_to_int(255, 0, 255, 50))
polygon.strokeColor = rint(rgba_to_int(255, 255, 0))
polygon.strokeWidth = omero.model.LengthI(10, UnitsLength.PIXEL)
points = "10,20, 50,150, 200,200, 250,75"
polygon.points = rstring(points)
create_roi(image, [polygon])
```

Can you confirm which version of omero-server you're running?

**Comment by erickmartins** [comment]
I can confirm the problem with ezomero 2.1.0, OMERO.server 5.6.9. I personally blame @joshmoore 😆 

Now more seriously, it seems like something _did_ change on OMERO's side that I was not aware of. I'll include a fix and update ezomero to use the latest omero-py version on the next release.

**Comment by erickmartins** [comment]
(I have just tested it against OMERO.server 5.6.9 and also had no issues)

**Comment by n-loureiro** [comment]
Hi @erickmartins , 
Thanks a lot for updating it! And yes, I'm using the latest version of [omero-py](https://github.com/ome/omero-py) and [omero-web](https://github.com/ome/omero-web).

**Comment by erickmartins** [comment]
Thanks. I am out of ideas on this one - I've also tried manually updating omero-py to latest (ezomero wants 5.13.1) and had no issue either. Had a coworker try the same workflow on a completely different server, with different versions of everything, and it worked fine as well. The only thing I can think of is OMERO Plus, but I don't think that should make a difference. Is your OMERO.server also latest?

**Comment by erickmartins** [comment]
(a decent sanity check might be to run the docker-compose on this repo (`docker-compose -f ezomero/tests/docker-compose.yml up -d`) and try it against that server instead)

**Comment by erickmartins** [comment]
hmm, interesting. ezomero is directly creating a `PolygonI` object via omero-py, and apparently using comma-separated points works most of the time (though clearly not always, as this issue shows). We should make it compliant with the OME data model and use space-separated points, but I'm really curious about why 1) omero-py accepts comma-separated 2) for some people that breaks!

**Comment by sbesson** [comment]
I think the core issue is that there is little constraint on the `[Polygon|Polyline].points` attribute other than being a `text` at the OMERO model definition - see https://github.com/ome/omero-model/blob/v5.6.12/src/main/resources/mappings/roi.ome.xml#L108. 

In practice, this means that the OMERO API level will not validate the format of these values when saving them to the database and it is possible to store nonsensical strings e.g.:

```
$ omero obj get Polygon:2202 points
Using session for import.user@localhost:4064. Idle timeout: 10 min. Current group: Demo Group
10,10 10,20 20,20 20,10 10,10
$ omero obj update Polygon:2202 points="10,10 10,20 20,20 10,10"
Using session for import.user@localhost:4064. Idle timeout: 10 min. Current group: Demo Group
Polygon:2202
$ omero obj get Polygon:2202 points
Using session for import.user@localhost:4064. Idle timeout: 10 min. Current group: Demo Group
10,10 10,20 20,20 10,10
$ omero obj update Polygon:2202 points="a list of points"
Using session for import.user@localhost:4064. Idle timeout: 10 min. Current group: Demo Group
Polygon:2202
$ omero obj get Polygon:2202 points
Using session for import.user@localhost:4064. Idle timeout: 10 min. Current group: Demo Group
a list of points
```

**Comment by erickmartins** [comment]
Gotcha. So it's not that it breaks for some people; it's that only certain clients will read the non-compliant string as valid. Thanks! PR to fix it is opened already.
